CREATE TABLE IF NOT EXISTS `schedule` (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  cityName text,
  userID varchar(20),
  FOREIGN KEY(userID) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
);